#!/bin/bash
ls *.csv | sed 's/.csv//'

while true; do
    read -p "Do you wish to move these files to the entered directory?" yn
    case $yn in
        [Yy]* ) mv *.csv entered/; break;; 
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

