#!/bin/bash

# Reads lines, prepends a timestamp and appends an optional delimiter
#
#
#
# Start a new file every serial number, so as soon as we encounter a serial number,
# store it, and use it as the output filename.
# Any scanned data is appended to that file
# q quits
# n next DUO
# t timestamp


VERSION="1.0.0-beta1" 

while getopts "n:o:" option
do
  case "${option}"
  in
    o) OUTDIR=${OPTARG};;
    n) BUILDER=${OPTARG};;
  esac
done

echo "Scancsv version $VERSION"
echo


# if outdir does not exist, exit with a message
if [[ ! -d "$OUTDIR" ]]; then
  echo "Output directory specified with -o does not exist. Exiting."
  exit 2
fi
cd "$OUTDIR"

echo "What is your name?"
read name
BUILDER="$name"

while :
do
  echo "Name: $BUILDER"
  echo "Enter serial number: press q to quit"
  read SERIAL 
  case $SERIAL in
    'q') exit 0;;
    ''|*[!0-9]*) echo "not a number"; continue;;
    *) echo "Logging steps for serial no $SERIAL" ;;
  esac

  date "+%Y-%m-%d %H:%M:%S,$BUILDER" >> "$SERIAL".cs~
  date "+%Y-%m-%d %H:%M:%S,start" >> "$SERIAL".cs~

  while :
  do
    read
    if [ "$REPLY" == "q" ]; then
      exit 0
    elif [ "$REPLY" == "n" ]; then
      echo "$SERIAL is done!"
      mv "$SERIAL".cs~ "$SERIAL".csv
      echo
      break
    elif [ "$REPLY" == "t" ]; then
      date "+%Y-%m-%d %H:%M:%S" >> "$SERIAL".cs~
    else
      date "+%Y-%m-%d %H:%M:%S,$REPLY" >> "$SERIAL".cs~
    fi
  done
done
